### ISSUE TITLE
Getting artifacts on the images

### ISSUE THREAD

**Issue by MostHated** [jomo/imgur-screenshot#139] opened 2019-04-28 16:20 UTC
Hey there,
    I used to use MyImgur multiple times a day when I was on Windows, so was really glad to have found this! I am having a bit of an issue though. Most  of the time, when I hit the shortcut to activate this, my mouse cursor doesn't change, and I can't see the outline while dragging, so I just have to hope it's working. Then also, not all the time, but occasionally I end up with images that have bits and pieces of the outline from dragging imposed onto the image randomly in places in which I have dragged over as seen here:

![](https://i.imgur.com/ZKpBpio.png)

My system is as seen below.
```
             /////////////                mosthated@mosthated-pc 
         /////////////////////            ---------------------- 
      ///////*767////////////////         OS: Pop!_OS 19.04 x86_64 
    //////7676767676*//////////////       Host: MS-7B79 2.0 
   /////76767//7676767//////////////      Kernel: 5.0.0-13-generic 
  /////767676///*76767///////////////     Uptime: 1 day, 9 hours, 31 mins 
 ///////767676///76767.///7676*///////    Packages: 2714 (dpkg), 8 (snap) 
/////////767676//76767///767676////////   Shell: bash 5.0.3 
//////////76767676767////76767/////////   Resolution: 1920x1080, 2560x1080, 1920x1080 
///////////76767676//////7676//////////   DE: GNOME 3.32.0 
////////////,7676,///////767///////////   WM: GNOME Shell 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-slim-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Adwaita [GTK2/3] 
  //////////////////////'////////////     Terminal: yakuake 
   //////.7676767676767676767,//////      Terminal Font: Consolas 10 
    /////767676767676767676767/////       CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz 
      ///////////////////////////         GPU: NVIDIA GeForce RTX 2070 
         /////////////////////            Memory: 10045MiB / 32175MiB 
             /////////////
                                                                  

```

**Comment by jomo** [comment] 2019-04-28 16:25
duplicate of #32, #75, #77, #108, #121, #132

**Closed by jomo** 2019-04-28 16:25 UTC

**Comment by MostHated** [comment] 2019-04-28 16:40
I had to use python2.x, but was able to install and get that working. 

Thanks,
-MH
